---
title: Quantum Institutes For All
author: Whirl
date: '2020-08-29'
slug: quantum-institutes
categories: []
tags: []
draft: no
---

Quantum twitter exploded in a hubbub this past Wednesday when the Department of 
Energy, on behalf of the Trump Administration, announced the formation of 5 new 
Quantum Information Science centers with an accompanying award of $925 million. 
The details, available both in this <a href="https://venturebeat.com/2020/08/26/white-house-announces-creation-of-ai-and-quantum-research-institutes/amp/?__twitter_impression=true">VentureBeat</a> article, and directly
from the <a href="https://www.energy.gov/articles/white-house-office-technology-policy-national-science-foundation-and-department-energy">DOE press-release</a> indicate that about 
$300 million of the total award will come from industry and academic partners, with the
remaining $625 million to be contributed by the DOE. Interestingly, the VB article
claims that the entirety of the $625 million is coming from funds earmarked in the 
National Quantum Initiative Act from 2018. This seems plausible, I certainly haven't 
heard anything about how the NQIA money was supposed to be spent. If this is true,
then no new money has entered the field, but at least the earmarked funds are being deployed. 

The VB article ends with some gloom, taking the position that

<blockquote> But U.S. superiority in AI and quantum computing is an increasingly dim prospect. The EU Commission has committed to increasing investment in AI from \$565 million (€500 million) in 2017 to \$1.69 billion (€1.5 billion) by the end of 2020. France recently took the wraps off a \$1.69 billion (€1.5 billion) initiative aimed at transforming the country into a “global leader” in AI research and training. And in 2018, South Korea unveiled a multiyear, $1.95 billion (KRW 2.2 trillion) effort to strengthen its R&D in AI, with the goal of establishing six AI-focused graduate schools by 2022 and training 5,000 AI specialists. </blockquote>

For quantum information this is obvious scaremongering. If you read the most recent
<a href="https://www.whitehouse.gov/wp-content/uploads/2017/12/Artificial-Intelligence-Quantum-Information-Science-R-D-Summary-August-2020.pdf#_blank"> AI and QIS R&D summary</a> from the
White House Office of Science and Technology Policy, you will see that the spending is 
*specifically* designated as 'non-defense' spending. The ~$579 million allocated for quantum information is basically on par with what we've been seeing out of the EU public sector spend.
I think the monetary advantage is still heavily in the United States' favor, because defense spending on quantum technologies must be enormous. You'll note that basically every even marginally useful quantum paper published in the last 15 years has an acknowledgment section that mentions some service branch's research office or research laboratories, or an entity like DARPA. ARO, AFRL, NFRL, etc have all had their fingers in this pie for a long time, both as funding agencies and researchers. For instance, the Air Force and Army research labs have published on various facets of quantum communications, and it is well known that the Navy is quite interested in quantum position, navigation, and timing technologies.

It's impossible to speculate how many classified dollars are being spent on this, but with government contractors like Honeywell and Raytheon, as well as government labs like Sandia actively pursuing research programs, you can bet it is substantial. 
Further, Google alone could fund a quantum research program worthy of a small nation from its $100 billion dollar pile of cash that it's sitting on. In short, I don't see a compelling argument for any sort of 'funding gap' when it comes to quantum information in the United States.

<h2>The Quantum Centers</h2>

The weirdest thing about this announcement is the structure and purported responsibilities of these quantum centers. Descriptions and links to the actual center websites can be found
<a href="https://science.osti.gov/Initiatives/QIS/QIS-Centers"> here</a>. I will reproduce the brief blurbs below for convenience.

<blockquote>

<h3><a href="https://science.osti.gov/Leaving-Office-of-Science?url=https%3a%2f%2fwww.q-next.org%2f&external=true">Q-NEXT · Next Generation Quantum Science and Engineering</a></h3>

**Director**: David Awschalom

**Lead Institution**: Argonne National Laboratory

Q-NEXT will create a focused, connected ecosystem to deliver quantum interconnects, to establish national foundries, and to demonstrate communication links, networks of sensors, and simulation testbeds. In addition to enabling scientific innovation, Q-NEXT will build a quantum-smart workforce, create quantum standards by building a National Quantum Devices Database, and provide pathways to the practical commercialization of quantum technology by embedding industry in all aspects of its operations and incentivizing start-ups.</blockquote>

Ok, seems fine. Q-NEXT is kind of an accelerator/incubator. It turns out that these quantum foundries are going to be located at Argonne and near SLAC, which is weird when a lot of large scale quantum device fabrication is already occuring at other government labs. Lincoln Laborator in particular, is known to be an excellent superconducting electronics foundry, which has one of the most advanced processes outside of Google/Rigetti/IBM. 

<blockquote>
<h3><a href="https://science.osti.gov/Leaving-Office-of-Science?url=https%3a%2f%2fwww.bnl.gov%2fquantumcenter%2f&external=true">C<sup>2</sup>QA · Co-design Center for Quantum Advantage</a></h3>

**Director**: Steve Girvin

**Lead Institution**: Brookhaven National Laboratory

C<sup>2</sup>QA aims to overcome the limitations of today’s noisy intermediate scale quantum (NISQ) computer systems to achieve quantum advantage for scientific computations in high-energy, nuclear, chemical and condensed matter physics. The integrated five-year goal of C2QA is to deliver a factor of 10 improvement in each of software optimization, underlying materials and device properties, and quantum error correction, and to ensure these improvements combine to provide a factor of 1,000 improvement in appropriate computation metrics.
</blockquote>

I think a 10x improvement in any one of these tasks could would be formidable, but all three is a gargantuan undertaking. There's a decent chance we'll see breakthroughs here, since the <a href="https://www.bnl.gov/quantumcenter/team.php">C<sup>2</sup>QA team</a> is made up of extremely accomplished researchers across the quantum computation/information fields. In fact, Andrew Houck, whose lab produced the first paper characterizing tantalum qubits <a href="https://whirlwind.netlify.app/2020/04/26/a-tantalizing-approach-to-better-qubits/">(here's my write-up)</a>, is the deputy director of C<sup>2</sup>QA. So when a totally new material for fabrication process is invented at C<sup>2</sup>QA, do they set up their own foundry which will compete with Q-NEXT foundries? Will the quantum centers be collaborating with each other? How, specifically, will that collaboration look?


<blockquote>
<h3><a href="https://science.osti.gov/Leaving-Office-of-Science?url=https%3a%2f%2fsqms.fnal.gov%2f&external=true">SQMS · Superconducting Quantum Materials and Systems Center</a></h3>

**Director**: Anna Grassellino

**Lead Institution**: Fermi National Accelerator Laboratory

The primary mission of SQMS is to achieve transformational advances in the major crosscutting challenge of understanding and eliminating the decoherence mechanisms in superconducting 2D and 3D devices, with the goal of enabling construction and deployment of superior quantum systems for computing and sensing. In addition to the scientific advances, SQMS will target tangible deliverables in the form of unique foundry capabilities and quantum testbeds for materials, physics, algorithms, and simulations that could broadly serve the national QIS ecosystem.
</blockquote>

It's hard to see how this mission is different from a combination of the Centers described above. Understanding and eliminating decoherence mechanisms in superconducting devices is guaranteed to be a materials problems, so effectively no different than the C<sup>2</sup>QA mission to improve "underlying materials and device" properties by 10x. The device properties you care about are usually the coherence of the qubits and the overall system! Is SQMS going to deliver foundry capabilities, too?


<blockquote>
<h3><a href="https://thequantuminformationedge.org">QSA · Quantum Systems Accelerator</a></h3>

**Director**: Irfan Siddiqi

**Lead Institution**: Lawrence Berkeley National Laboratory

QSA aims to co-design the algorithms, quantum devices, and engineering solutions needed to deliver certified quantum advantage in scientific applications. QSA’s multi-disciplinary team will pair advanced quantum prototypes—based on neutral atoms, trapped ions, and superconducting circuits—with algorithms specifically constructed for imperfect hardware to demonstrate optimal applications for each platform in scientific computing, materials science, and fundamental physics. The QSA will deliver a series of prototypes to broadly explore the quantum technology trade-space, laying the basic science foundation to accelerate the maturation of commercial technologies.
</blockquote>

This seems a LOT like the mission statement for C<sup>2</sup>QA, except they couldn't use the
NISQ acronym (ironic, because John Preskill, who coined it, is a member of QSA), so they had to go with and oblique reference with the phrase "imperfect hardware". This is the most generic of the mission statements, but if you read the QSA <a href="https://thequantuminformationedge.org/vision/">Vision</a> you'll see an emphasis on hardware, software, and 'co-design'. The latter is emphasized heavily in the <a href="https://www.bnl.gov/quantumcenter/research.php">C<sup>2</sup>QA</a> research statement, as well.

<blockquote>
<h3><a href="https://science.osti.gov/Leaving-Office-of-Science?url=https%3a%2f%2fqscience.org%2f&external=true">QSC · The Quantum Science Center</a></h3>

**Director**: David Dean

**Lead Institution**: Oak Ridge National Laboratory

QSC is dedicated to overcoming key roadblocks in quantum state resilience, controllability, and ultimately scalability of quantum technologies. This goal will be achieved through integration of the discovery, design, and demonstration of revolutionary topological quantum materials, algorithms, and sensors, catalyzing development of disruptive technologies. In addition to the scientific goals, integral to the activities of the QSC are development of the next generation of QIS workforce by creating a rich environment for professional development and close coordination with industry to transition new QIS applications to the private sector.
</blockquote>

I'm sure you have detected the pattern by now. Again, this mission statement is basically the same as all of the others. As far as I can tell, the formation of the quantum centers is less about having some sort of "national plan" for quantum information science, and more about formalizing that everyone will keep doing what they're doing. I suspect that the substantial sums involved in funding the centers allows for additional flexibility, where research efforts are not beholden to vagaries of short-term DARPA/DOE/IARPA/NSF program managers, but can be better directed by people closer to the actual research itself. 

It's also interesting that there are multiple representatives from private industry on the steering committees for these centers. Microsoft, Rigetti, IBM, AMD, Volkswagen and others all have a formal partnership with at least one of these centers. This seems to go beyond the loose, wary association the members of the Quantum Economic Development Consortium (QED-C) had with each other. 

In the end, I expect the proliferation of a lot of 'redundant' capabilities, where multiple different foundries spring up specializing in different kinds of devices or materials. I would love to see tight collaboration between the quantum centers, not just within them, as a way of accelerating progress across the field. Again, merely publishing papers is insufficient. Actual people need to get together and learn about the critical details that are always omitted from papers. Failures rarely get published, but are often more instructive than successes at driving learning.

From a strategic perspective, I think forming these quantum centers is the right approach, at least for a society that does not rely on central planning. Dictating the direction of QIS research is essentially wasted effort, since we don't know what shape the first, or even the tenth, quantum computer will take. We *do* know which component areas need improvement and in what ways. For me, the establishment of these quantum centers signals a continuing commitment to publicly funding and promoting quantum technologies, even if it doesn't materially change how the research is organized and pursued. 

