---
title: "Quantum Institutes For All"
author: "Whirl"
date: 2020-08-29
draft: true
---

Quantum twitter exploded in a hubbub this past Wednesday when the Department of 
Energy, on behalf of the Trump Administration, announced the formation of 5 new 
Quantum Information Science centers with an accompanying award of $925 million. 
The details, available both in this <a href="https://venturebeat.com/2020/08/26/white-house-announces-creation-of-ai-and-quantum-research-institutes/amp/?__twitter_impression=true">VentureBeat</a> article, and directly
from the <a href="https://www.energy.gov/articles/white-house-office-technology-policy-national-science-foundation-and-department-energy">DOE press-release</a> indicate that about 
$300 million of the total award will come from industry and academic partners, with the
remaining $625 million to be contributed by the DOE. Interestingly, the VB article
claims that the entirety of the $625 million is coming from funds earmarked in the 
National Quantum Initiative Act from 2018. This seems plausible, I certianly haven't 
heard anything about how the NQI act money was supposed to be spent. If this is true,
then no new money has entered the field, but at least now it is being deployed. 

The VB article ends with some gloom, taking the position that

<blockquote> But U.S. superiority in AI and quantum computing is an increasingly dim prospect. The EU Commission has committed to increasing investment in AI from \$565 million (€500 million) in 2017 to \$1.69 billion (€1.5 billion) by the end of 2020. France recently took the wraps off a \$1.69 billion (€1.5 billion) initiative aimed at transforming the country into a “global leader” in AI research and training. And in 2018, South Korea unveiled a multiyear, $1.95 billion (KRW 2.2 trillion) effort to strengthen its R&D in AI, with the goal of establishing six AI-focused graduate schools by 2022 and training 5,000 AI specialists. </blockquote>

At least for quantum information, this is obvious scaremongering. If you read the most recent
<a href="https://www.whitehouse.gov/wp-content/uploads/2017/12/Artificial-Intelligence-Quantum-Information-Science-R-D-Summary-August-2020.pdf#_blank"> AI and QIS R&D summary</a> from the
White House Office of Science and Technology Policy, you will see that the spending is 
*specifically* designated as 'non-defense' spending. The ~$579 million allocated for quantum information is basically on par with what we've been seeing out of the EU public sector spend.
I think the monetary advantage is still heavily in the United States' favor, because defense spending on quantum technologies must be enormous. You'll note that basically every even marginally useful quantum paper published in the last 15 years has an acknowledgement section that mentions some service branche's research office or research laboratories, or an entity like DARPA. ARO, AFRL, NFRL, etc have all had their fingers in this pie for a long time, both as funding agencies (DARPA, ARO) and researchers. Both the Air Force and Army research labs have published on various facets of quantum communications, and it is well known that the Navy is quite interested in quantum position, navigation, and timing technologies. 
It's impossible to speculate how many classified dollars are being spent on this, but with government contractors like Honeywell and Raytheon, as well as government labs like Sandia actively pursuing research programs, you can bet it is substantial. 
Further, Google alone could fund a quantum research program worthy of a small nation from its $100 billion dollar pile of cash that it's sitting on. In short, I don't see a compelling argument for any sort of 'funding gap' when it comes to quantum information in the United States.

##The Quantum Centers

